version: '3.8'

services:
  gradio_app:
    build: ./gradio_app
    container_name: gradio-app
    ports:
      - "7860:7860"
    volumes:
      - ./gradio_app:/app
    depends_on:
      - mongodb

  # worker:
  #   build: ./worker
  #   volumes:
  #     - ./worker:/app
  #   depends_on:
  #     - mongodb

  mongodb:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
