# TANDEM 
  # gradio_app: port 7861
# TANDEM-dev : port 7862

services:
  gradio_app:
    # platform: linux/amd64
    build: ./gradio_app
    container_name: gradio_app_dev
    ports:
      - "7862:7861"
    volumes:
      - ./gradio_app:/gradio_app
      - ./tandem:/tandem
    depends_on:
      - mongodb
      - worker
      - tandem
    labels:
      owner: "yang_loci"
      project: "tandem_website_dev"

  tandem:
    platform: linux/amd64
    build: ./tandem
    container_name: tandem_dev
    expose:
      - "5000"   # internal only; not mapped to host
    depends_on:
      - mongodb
    volumes:
      # Mount the external git repo into expected paths
      - ./tandem:/tandem
      - ./gradio_app:/gradio_app
    labels:
      owner: "yang_loci"
      project: "tandem_website_dev"

  worker:
    # platform: linux/amd64
    build: ./worker
    container_name: worker_dev
    depends_on:
      - mongodb
      - tandem
    volumes:
      - ./worker:/worker
      - ./tandem:/tandem
    labels:
      owner: "yang_loci"
      project: "tandem_website_dev"

  mongodb:
    # platform: linux/amd64
    image: mongo:4.4
    container_name: mongodb_dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    labels:
      owner: "yang_loci"
      project: "tandem_website_dev"

volumes:
  mongo_data:
  shared_results: