# Architecture: x86_64
name: tandem
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hfdf4475_7
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - gsl=2.7=h93259b0_0
  - hmmer=3.4=hc70aa7a_4
  - libblas=3.9.0=31_h7f60823_openblas
  - libcblas=3.9.0=31_hff6cab4_openblas
  - libcxx=20.1.4=hf95d169_0
  - libexpat=2.7.0=h240833e_0
  - libffi=3.4.6=h281671d_1
  - libgfortran=14.2.0=hef36b68_105
  - libgfortran5=14.2.0=h58528f3_105
  - liblzma=5.8.1=hd471939_0
  - libopenblas=0.3.29=openmp_hbf64a52_0
  - libsqlite=3.49.1=hdb6dae5_2
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=20.1.4=ha54dae1_0
  - mpi=1.0=openmpi
  - ncurses=6.5=h0622a9a_3
  - openmpi=4.1.6=h7406208_101
  - openssl=3.5.0=hc426f3f_1
  - pip=25.1.1=pyh8b19718_0
  - python=3.11.11=h9ccd52b_2_cpython
  - readline=8.2=h7cca4af_2
  - setuptools=80.1.0=pyhff2d567_0
  - tk=8.6.13=h1abcd95_1
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zlib=1.3.1=hd23fc13_2
  - pip:
      - beautifulsoup4==4.13.4
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - filelock==3.18.0
      - gdown==5.2.0
      - idna==3.10
      - pysocks==1.7.1
      - requests==2.32.3
      - soupsieve==2.7
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - urllib3==2.4.0
prefix: /opt/anaconda3/envs/tandem
